apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: userdata-servicemonitor
  namespace: monitoring
  labels:
    release: kube-prom
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: backend-userdata
  endpoints:
    - port: metrics
      path: /actuator/prometheus
      interval: 30s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: apigate-servicemonitor
  namespace: monitoring
  labels:
    release: kube-prom
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: backend-apigate
  endpoints:
    - port: metrics
      path: /actuator/prometheus
      interval: 30s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: suggest-servicemonitor
  namespace: monitoring
  labels:
    release: kube-prom
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: backend-suggest
  endpoints:
    - port: metrics
      path: /actuator/prometheus
      interval: 30s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-servicemonitor
  namespace: monitoring
  labels:
    release: kube-prom
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: frontend
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
