# Minimal kube-prometheus-stack values for small test cluster
prometheus:
  prometheusSpec:
    retention: "7d"
    resources:
      requests:
        cpu: "100m"
        memory: "200Mi"
      limits:
        cpu: "300m"
        memory: "500Mi"
    # reduce replicas (single-node labs)
    replicas: 1
    # small disk to avoid huge usage
    storageSpec:
      emptyDir: {}

grafana:
  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
      serve_from_sub_path: true
  enabled: true
  adminUser: admin
  adminPassword: changeme123          # change in production or use secret
  persistence:
    enabled: false
  ingress:
    enabled: false  # we provide a separate ingress manifest; switch to true if prefer helm-managed ingress

prometheusOperator:
  tlsProxy:
    enabled: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

alertmanager:
  enabled: true
