name: Infra Apply (Day-0 & Day-N)

on:
  workflow_dispatch:         # Day-0: trigger manually
  push:                      # Day-N: auto-apply when infra YAMLs change
    branches: [ "master" ]

jobs:
  apply:
    runs-on: [self-hosted, linux, X64]     # your org-level EC2 runner
    steps:
      - uses: actions/checkout@v4

      # ---- Day-0 bootstrap (idempotent) ----
      - name: Bootstrap machine if needed
        run: |
          set -euo pipefail
          echo "Checking if bootstrap is needed..."
          if ! command -v kubectl >/dev/null 2>&1 || ! kubectl get nodes >/dev/null 2>&1; then
            echo "Running bootstrap.sh (install JDK, Maven, Docker, Kubernetes)..."
            sudo bash ./bootstrap.sh
          else
            echo "Bootstrap not needed. kubectl and cluster are ready."
          fi

      # ---- Secrets (safe to re-run) ----
      - name: Create/Update AWS Secret
        run: |
          kubectl create secret generic aws-secrets \
            --from-literal=AWS_ACCESS_KEY_ID='${{ secrets.AWS_ACCESS_KEY_ID }}' \
            --from-literal=AWS_SECRET_ACCESS_KEY='${{ secrets.AWS_SECRET_ACCESS_KEY }}' \
            --dry-run=client -o yaml | kubectl apply -f -

      # ---- Base infra ----
      - name: Apply Base
        run: kubectl apply -f base/

      # ---- Services ----
      - name: Apply Services
        run: kubectl apply -f services/

      # ---- Quick snapshot ----
      - name: Snapshot
        run: |
          kubectl get nodes
          kubectl get deploy,svc,ingress
          kubectl get pods -A


