name: Deploy Runner (Terraform) - post-apply registration

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Init
        working-directory: terra
        run: terraform init -input=false -no-color

      - name: Terraform Apply
        working-directory: terra
        run: terraform apply -auto-approve -input=false -no-color

      - name: Get runner public IP
        working-directory: terra
        id: tfout
        run: |
          IP=$(terraform output -raw runner_public_ip)
          echo "IP=$IP" >> "$GITHUB_OUTPUT"

      - name: Request fresh GitHub org registration token
        id: regtoken2
        run: |
          ORG="Recipies-Polyglot-Org"
          RESP=$(curl -s -X POST -H "Authorization: token ${{ secrets.GH_PAT }}" -H "Accept: application/vnd.github+json" "https://api.github.com/orgs/${ORG}/actions/runners/registration-token")
          TOKEN=$(echo "$RESP" | jq -r .token)
          if [ -z "$TOKEN" ] || [ "$TOKEN" = "null" ]; then
            echo "Failed to obtain registration token"
            echo "$RESP" >&2
            exit 1
          fi
          echo "token=$TOKEN" >> "$GITHUB_OUTPUT"

      - name: Register runner via SSH (use fresh token)
        id: sshreg
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          RUNNER_IP: ${{ steps.tfout.outputs.IP }}
          REG_TOKEN: ${{ steps.regtoken2.outputs.token }}
        run: |
          mkdir -p /tmp/sshkey
          chmod 700 /tmp/sshkey
          echo "$SSH_KEY" > /tmp/sshkey/id_rsa
          chmod 600 /tmp/sshkey/id_rsa

          # small pause for cloud-init to finish
          sleep 10

          # pass token via stdin into remote bash; keep heredoc quoted so YAML doesn't expand it
          /bin/echo "$REG_TOKEN" | ssh -o StrictHostKeyChecking=no -i /tmp/sshkey/id_rsa ubuntu@"$RUNNER_IP" 'bash -s' <<'REMOTE'
set -euo pipefail
read TOKEN
cd /opt/actions-runner || { echo "runner dir not found"; exit 1; }
sudo -u githubrunner bash -lc "./config.sh --unattended --url https://github.com/Recipies-Polyglot-Org --token \"$TOKEN\" --name runner-manual-$(hostname)-$(date +%s) --labels self-hosted,linux,X64 --work _work --replace || true"

cat > /etc/systemd/system/github-runner.service <<'EOF'
[Unit]
Description=GitHub Actions Runner
After=network.target

[Service]
Type=simple
User=githubrunner
WorkingDirectory=/opt/actions-runner
ExecStart=/opt/actions-runner/run.sh
Restart=always
RestartSec=5s

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now github-runner.service || true
systemctl status github-runner.service --no-pager || true
REMOTE

          echo "registration ssh step completed"
